network_ether_interfaces:
  - device: enp1s0f1
    bootproto: static
    address: 192.168.0.242
    netmask: 255.255.255.0
    route:
      - network: 172.16.0.0
        netmask: 255.255.255.0
        gateway: 192.168.0.2
